name: CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "*"

jobs:
    pytest_build:
        runs-on: ubuntu-latest
        env:
          TERM: "linux"
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Setup Virtual Env
              shell: bash
              run: |
                python -m pip install -r requirements.txt
                python setup.py install
                py-clock -s -m