name: CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "*"

jobs:
    pytest_build:
        runs-on: ubuntu-latest
        env:
          TERM: "linux"
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Setup Virtual Env
              shell: bash
              run: |
                python -m venv venv
                source ./venv/bin/activate
                python -m pip install -r requirements.txt
            - name: Run PyTest
              shell: bash
              run: |
                source ./venv/bin/activate
                python -m pytest -v tests
            - name: Install CLI tool
              shell: bash
              run: |
                source ./venv/bin/activate
                python setup.py install
                py-clock -s -m -d